name: taskly
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  video_player: ^2.8.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.3
  supabase_flutter: ^2.1.2
  dio: ^5.3.2
  either_dart: ^1.0.0
  connectivity_plus: ^5.0.1
  injectable: ^2.1.5
  get_it: ^7.6.4
  loading_animation_widget: ^1.3.0
  animated_text_kit: ^4.2.2
  lottie: ^2.7.0
  dropdown_button2: ^2.3.9
  font_awesome_flutter: ^10.5.0
  flutter_spinbox: ^0.13.1
  uuid: ^4.2.1
  file_picker: ^9.0.1
  shared_preferences: ^2.2.2
  bloc: ^8.1.2
  intl: ^0.20.2
  google_sign_in: ^6.1.5
  open_file: ^3.3.3
  syncfusion_flutter_pdfviewer: ^31.1.19
  timeago: ^3.6.2
  shimmer: ^3.0.0
  marquee: ^2.2.3
  url_launcher: ^6.1.11
  sign_in_with_apple: ^7.0.1
  flutter_facebook_auth: ^7.1.2
  image_picker: ^1.1.0
  path_provider: ^2.1.2
  audioplayers: ^6.1.0
  permission_handler: ^12.0.1
  record: ^6.1.2
  flutter_rating_bar: ^4.0.1
  provider: ^6.1.5+1
  photo_view: ^0.15.0
  just_audio: ^0.10.5
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^19.4.2
  auto_size_text: ^3.0.0
  internet_connection_checker: ^1.0.0+1
  liquid_glass_easy: ^1.0.0
  marqueer: ^2.1.0
  flutter_launcher_icons: ^0.14.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.3.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/lotties/
    - assets/icons/

  

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300

    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-Light.ttf
          weight: 300


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"

  adaptive_icon_background: "#457F63"
  adaptive_icon_foreground: "assets/images/app_logo.png"